inherit ros_distro_${ROS_DISTRO}
inherit ros_component
inherit qprebuilt

# Consumer recipe: installs the prebuilt tarball generated by the higher-
# priority producer recipe in meta-qti-robotics-prop (priority 17 vs this
# layer's 13).  When both layers are present, BitBake selects the prop recipe.
# This recipe is used in SDK / customer builds where only the prebuilt tarball
# is available (no local source tree).
#
# qprebuilt anonymous python checks PREBUILT_SRC_DIR for a matching tarball
# (vio_${PV}_${PACKAGE_ARCH}.tar.gz, or any MACHINEOVERRIDES arch variant).
# When found it enables do_install_prebuilt and marks build tasks noexec.
include vio_prebuilts.conf

DESCRIPTION = "The visual inertial odometry ROS2 package"
HOMEPAGE         = "http://support.cdmatech.com"
LICENSE          = "Qualcomm-Technologies-Inc.-Proprietary"
LIC_FILES_CHKSUM = "file://${QCOM_COMMON_LICENSE_DIR}/${LICENSE};md5=388eae46b25133d68fbf4e1c7340abcc"

ROS_EXEC_DEPENDS = " \
    rclcpp \
    sensor-msgs \
    std-msgs \
    nav-msgs \
    geometry-msgs \
    cv-bridge \
    image-transport \
    rosidl-adapter \
    rclcpp-components \
    rcutils \
"
ROS_CN = "qrb_ros_vio"
ROS_BPN = "qrb_ros_vio"

# No source to fetch; do_fetch/unpack/patch/configure/compile/install are all
# marked noexec by qprebuilt when the tarball is found.
SRC_URI = ""

# Path where the producer recipe (meta-qti-robotics-prop) places the tarball:
#   ${DEPLOY_DIR}/prebuilts/HY22/vio_${PV}_${PACKAGE_ARCH}.tar.gz
PREBUILT_SRC_DIR = "${DEPLOY_DIR}/prebuilts/HY22"

# Drop all build-time dependencies; the prebuilt is already compiled.
PREBUILT_INHIBIT_DEPS = "1"

# Runtime dependencies only.
RDEPENDS:${PN} += "${ROS_EXEC_DEPENDS}"

ROS_BUILD_TYPE = "ament_cmake"
inherit ros_${ROS_BUILD_TYPE} robotics-package
INSANE_SKIP:${PN} += "file-rdeps already-stripped"
